apiVersion: v1
kind: Service
metadata: 
  name: dbmssqlitarch 
  namespace: default 
spec: 
  selector: 
    app: mssql 
  ports: 
    - protocol: TCP 
      port: 1433 
      targetPort: 1433 
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: dissertationmssqlef
  namespace: default 
  labels:
    app: dissertationmssqlef
spec:
  type: LoadBalancer
  ports:
    - name: http-api-port
      port: 80
  selector:
    app: dissertationmssqlef
