# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  ResourceGroupLocation: resourceGroup().location
  tag: '$(Build.BuildId)'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '-powershell: Get-ChildItem -Path ''Insert root path'' -recurse'
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'DevOps Permission'
    ScriptType: 'FilePath'
    ScriptPath: './AzureResourceGroupDeployment/Deploy-AzureResourceGroup.ps1'
    ScriptArguments: '-TemplateFile AzureResourceGroupDeployment/Website.json'
    azurePowerShellVersion: 'LatestVersion'
