# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: '6a0bacec-b436-4cc3-ba04-2e978d782706'
    ScriptType: 'FilePath'
    ScriptPath: './Deploy-AzureResourceGroup.ps1'
    ScriptArguments: -TemplateFile Website.json
    azurePowerShellVersion: 'LatestVersion'
