apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: dbmssqlitarch
  name: dbmssqlitarch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dbmssqlitarch
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: dbmssqlitarch
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: Ta11a6ht07022022!
          image: mcr.microsoft.com/mssql/server
          name: dbmssqlitarch
          ports:
            - containerPort: 1433
          resources: {}
      restartPolicy: Always
status: {}
