apiVersion: v1
kind: Service
metadata: 
  name: dbmssqlitarch 
  namespace: default 
spec: 
  selector: 
    app: mssql 
  ports: 
    - protocol: TCP 
      port: 1433 
      targetPort: 1433 
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: dissertationmssqlef
  namespace: default 
  labels:
    app: dissertationmssqlef
spec:
  type: LoadBalancer
  ports:
    - name: lb-api-port
      port: 80
  selector:
    app: dissertationmssqlef

---

apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mssql-deployment 
  namespace: default 
spec: 
  replicas: 1 
  selector: 
     matchLabels: 
       app: mssql 
  template: 
    metadata: 
      labels: 
        app: mssql 
    spec: 
      terminationGracePeriodSeconds: 30 
      hostname: mssqlinst 
      securityContext: 
        fsGroup: 10001 
      containers: 
      - name: mssql 
        image: mcr.microsoft.com/mssql/server:2019-latest 
        ports: 
        - containerPort: 1433 
        env: 
        - name: MSSQL_PID 
          value: "Developer" 
        - name: ACCEPT_EULA 
          value: "Y" 
        - name: SA_PASSWORD 
          value: Ta11a6ht07022022! 
        volumeMounts: 
        - name: mssqldb 
          mountPath: /var/opt/mssql 
      volumes: 
      - name: mssqldb 
        persistentVolumeClaim: 
          claimName: mssql-data 


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dissertationmssqlef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dissertationmssqlef
  strategy: {}
  template:
    metadata:
      labels:
        app: dissertationmssqlef
    spec:
      containers:
        - image: adocontainerrp.azurecr.io/dissertationmssqlef:v2
          name: dissertationmssqlef
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
      imagePullSecrets:
        - name: diss-acr-secret
      restartPolicy: Always
status: {}
