kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: mssql-data2 
  namespace: default 
  annotations: 
    volume.beta.kubernetes.io/storage-class: azure-disk 
spec: 
  accessModes: 
  - ReadWriteOnce 
  resources: 
    requests: 
      storage: 8Gi
      
--- 

apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mssql-deployment2
  namespace: default 
spec: 
  replicas: 1 
  selector: 
     matchLabels: 
       app: mssql2
  template: 
    metadata: 
      labels: 
        app: mssql2
    spec: 
      terminationGracePeriodSeconds: 30 
      hostname: mssqlinst 
      securityContext: 
        fsGroup: 10001 
      containers: 
      - name: mssql2
        image: mcr.microsoft.com/mssql/server:2019-latest 
        ports: 
        - containerPort: 1433 
        env: 
        - name: MSSQL_PID 
          value: "Developer" 
        - name: ACCEPT_EULA 
          value: "Y" 
        - name: SA_PASSWORD 
          value: Ta11a6ht07022022!
        volumeMounts: 
        - name: mssqldb2
          mountPath: /var/opt/mssql 
      volumes: 
      - name: mssqldb2
        persistentVolumeClaim: 
          claimName: mssql-data2


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapijwtazureauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapijwtazureauth
  strategy: {}
  template:
    metadata:
      labels:
        app: webapijwtazureauth
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '80'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - image: adocontainerrp.azurecr.io/webapijwtazureauth:v1
          name: dissertationmssqlef
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
      imagePullSecrets:
        - name: diss-acr-secret
      restartPolicy: Always
status: {}