apiVersion: v1
kind: Service
metadata: 
  name: dbmssqlitarchjwt
  namespace: default 
spec: 
  selector: 
    app: mssql2 
  ports: 
    - protocol: TCP 
      port: 1422
      targetPort: 1422 
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: webapijwtazureauth
  namespace: default 
  labels:
    app: webapijwtazureauth
spec:
  type: LoadBalancer
  ports:
    - name: lb-api-port
      port: 80
  selector:
    app: webapijwtazureauth

---

apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: ingress-jwt
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: "https://sts.windows.net/7be57bbd-1168-4d0f-b36f-87a4b67594de/"
    jwksUri: "https://login.microsoftonline.com/common/discovery/v2.0/keys"
    
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: routerouting
  namespace: default
spec:
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /headers
      headers:
        "@request.auth.principal":
          exact: https://login.microsoftonline.com/7be57bbd-1168-4d0f-b36f-87a4b67594de/v2.0
    route:
    - destination:
        host: webapijwtazureauth
